token: place your token here

bank rates links:
  VTB: https://www.vtb.ru/personal/platezhi-i-perevody/obmen-valjuty/#konv
  SberBank: https://www.sberbank.ru/ru/quotes/currencies?tab=sbol
  Tinkoff: https://www.tinkoff.ru/about/exchange/